#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 70)
    lines.append("  OceanBase Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  OceanBase Version: {env.get('software_version', 'N/A')}")
        lines.append(f"  Python Version:    {env.get('python_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:           {env.get('kernel', 'N/A')}")
        lines.append("")

    benchmarks = data.get("benchmarks", {})
    primary = benchmarks.get("primary", {})
    if primary:
        lines.append("  --- OLTP Benchmark (Primary, via sysbench) ---")
        lines.append(f"  Description:       {primary.get('description', 'N/A')}")
        params = primary.get("parameters", {})
        lines.append(f"  Workloads:          {params.get('workloads', 'N/A')}")
        lines.append(f"  Thread levels:     {params.get('thread_levels', 'N/A')}")
        lines.append(f"  Tables:             {params.get('tables', 'N/A')}")
        lines.append(f"  Table size:         {params.get('table_size', 'N/A')} rows")
        lines.append(f"  Time per test:     {params.get('time_per_test', 'N/A')}s")
        lines.append(f"  Connection:        {params.get('connection', 'N/A')}")
        lines.append("")
        rs = primary.get("results_summary", {})
        for wl in sorted(rs.keys()):
            wl_data = rs[wl]
            if not isinstance(wl_data, dict):
                continue
            lines.append(f"  [{wl}]")
            for tl in sorted(wl_data.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                e = wl_data[tl]
                if isinstance(e, dict) and e:
                    lines.append(f"    {tl:<14}: tps={e.get('tps', 'N/A')}, qps={e.get('qps', 'N/A')}, "
                                 f"avg_lat={e.get('avg_latency_ms', 'N/A')}ms, p95={e.get('p95_latency_ms', 'N/A')}ms")
            lines.append("")

    micro = benchmarks.get("micro", {})
    if micro:
        lines.append("  --- Micro Benchmarks ---")
        mresults = micro.get("results", {})
        if isinstance(mresults, dict):
            ts = mresults.get("thread_scaling", {})
            if isinstance(ts, dict) and ts:
                lines.append("  Thread scaling (oltp_point_select):")
                for tcl in sorted(ts.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                    e = ts[tcl]
                    if isinstance(e, dict) and e:
                        lines.append(f"    {tcl:<14}: QPS={e.get('qps', 'N/A')}, p95={e.get('p95_latency_ms', 'N/A')}ms")
            tc = mresults.get("table_count_sweep", {})
            if isinstance(tc, dict) and tc:
                lines.append("  Table count sweep (oltp_point_select @ t=16):")
                for tcl in sorted(tc.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                    e = tc[tcl]
                    if isinstance(e, dict) and e:
                        lines.append(f"    {tcl:<14}: QPS={e.get('qps', 'N/A')}, p95={e.get('p95_latency_ms', 'N/A')}ms")
        lines.append("")

    summary = data.get("summary", {})
    if summary:
        lines.append("  --- Overall Summary ---")
        if "avg_tps" in summary:
            lines.append(f"    Avg TPS:               {summary['avg_tps']}")
        if "max_tps" in summary:
            lines.append(f"    Max TPS:               {summary['max_tps']}")
        if "avg_qps" in summary:
            lines.append(f"    Avg QPS:               {summary['avg_qps']}")
        if "max_qps" in summary:
            lines.append(f"    Max QPS:               {summary['max_qps']}")
        if "read_write_tps_t16" in summary:
            lines.append(f"    Read/Write TPS (t=16): {summary['read_write_tps_t16']}")
        if "point_select_qps_t16" in summary:
            lines.append(f"    Point select QPS (t=16): {summary['point_select_qps_t16']}")
        if "thread_scaling_ratio" in summary:
            lines.append(f"    Thread scaling:        {summary['thread_scaling_ratio']}x")
        lines.append("")

    lines.append("=" * 70)
    lines.append("  Report generated by OceanBase Performance Benchmark Workflow")
    lines.append("=" * 70)

    summary_text = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary_text)
    print(summary_text)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)
    generate_summary(sys.argv[1], sys.argv[2])
