name: prometheus
category: cloud
description: Prometheus是云原生计算基金会（CNCF）项目，是一个系统和服务监控系统。它以给定的时间间隔从配置的目标收集指标，评估规则表达式，显示结果，并可以在观察到指定条件时触发警报。
environment: |
  本应用在Docker环境中运行，安装Docker执行如下命令
  ```
  yum install -y docker
  ```
tags: |
  Prometheus镜像的Tag由其版本信息和基础镜像版本信息组成，详细内容如下

  |    Tag   |  Currently  |   Architectures  |
  |----------|-------------|------------------|
  |[2.20.0-oe2203lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.20.0/22.03-lts/Dockerfile)| Prometheus server 2.20.0 on openEuler 22.03-LTS | amd64, arm64 |
  |[2.50.1-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.50.1/22.03-lts-sp3/Dockerfile)| Prometheus server 2.50.1 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[2.54.1-oe2003sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.54.1/20.03-lts-sp4/Dockerfile)| Prometheus server 2.54.1 on openEuler 20.03-LTS-SP4 | amd64, arm64 |
  |[2.54.1-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.54.1/22.03-lts-sp1/Dockerfile)| Prometheus server 2.54.1 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[2.54.1-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.54.1/22.03-lts-sp3/Dockerfile)| Prometheus server 2.54.1 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[2.54.1-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.54.1/22.03-lts-sp4/Dockerfile)| Prometheus server 2.54.1 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[2.54.1-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.54.1/24.03-lts/Dockerfile)| Prometheus server 2.54.1 on openEuler 24.03-LTS | amd64, arm64 |
  |[2.55.0-oe2003sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.0/20.03-lts-sp4/Dockerfile)| Prometheus server 2.55.0 on openEuler 20.03-LTS-SP4 | amd64, arm64 |
  |[2.55.0-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.0/22.03-lts-sp1/Dockerfile)| Prometheus server 2.55.0 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[2.55.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.0/22.03-lts-sp3/Dockerfile)| Prometheus server 2.55.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[2.55.0-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.0/22.03-lts-sp4/Dockerfile)| Prometheus server 2.55.0 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[2.55.0-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.0/24.03-lts/Dockerfile)| Prometheus server 2.55.0 on openEuler 24.03-LTS | amd64, arm64 |
  |[2.55.1-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.1/22.03-lts-sp1/Dockerfile)| Prometheus server 2.55.1 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[2.55.1-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.1/22.03-lts-sp3/Dockerfile)| Prometheus server 2.55.1 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[2.55.1-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.1/22.03-lts-sp4/Dockerfile)| Prometheus server 2.55.1 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[2.55.1-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/prometheus/2.55.1/24.03-lts/Dockerfile)| Prometheus server 2.55.1 on openEuler 24.03-LTS | amd64, arm64 |

download: |
  拉取镜像到本地
  ```
  docker pull openeuler/prometheus:{Tag}
  ```

usage: |
  - 启动容器
    ```
    docker run -d --name my-prometheus -p 9090:9090 openeuler/prometheus:{Tag}
    ```
    用户可根据自身需求选择对应版本的{Tag}、容器启动的选项。`my-prometheus`启动之后，通过`http://localhost:9090`访问Prometheus服务。
  
  - 启动参数

    |    Parameter   |  Description  |
    |----------------|---------------|
    | -p 9090:9090	 | 暴露Prometheus服务端口 |
    | -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml | 使用本地`prometheus.yml`配置文件 |
    | -v /path/to/alerts.yml:/etc/prometheus/alerts.yml | 使用本地`alerts.yml`配置文件 |

  - 容器测试

    查看运行日志
    ```
    docker logs -f my-prometheus
    ```

    使用shell交互
    ```
    docker exec -it my-prometheus /bin/bash
    ```

license: Apache-2.0 license
similar_packages:
  - Grafana: Grafana是一种流行的开源数据可视化工具，可以与多个数据源集成，包括Prometheus。它可以通过可视化仪表板展示和分析Prometheus收集的数据。
  - InfluxDB: InfluxDB是一种开源时间序列数据库，专门用于处理和存储大量时间序列数据，如机器指标、事件日志等。和Prometheus类似，InfluxDB也具备数据采集和查询功能。
  - Nagios: Nagios是一种广泛使用的开源网络监控系统，可以监测网络设备、服务器和应用程序的运行状况。与Prometheus不同的是，Nagios主要基于主动式监控，而不是Prometheus的基于抓取的方式。
  - Zabbix: Zabbix是一种功能强大的开源网络监控系统，可以监控各种网络设备、服务器和应用程序。它提供了多种监控方式，包括主动和被动式监控，并支持自定义的监控和警报设置。
  - Elastic Stack: Elastic Stack（前身是ELK Stack）是一个集成了Elasticsearch、Logstash和Kibana的解决方案，能够处理和分析大量的日志和指标数据。Elasticsearch可以用于存储和查询数据，Logstash用于数据采集和清洗，Kibana则提供了数据可视化和仪表板功能。
dependency:
  - Go