#!/usr/bin/env python3
import sys
import json
import os
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    if not os.path.exists(input_json):
        lines = [
            "=" * 70,
            "  petsc Performance Benchmark Report",
            "=" * 70,
            f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "  Status: INCOMPLETE - benchmark data not available",
            "=" * 70,
        ]
        summary = "\n".join(lines)
        os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
        with open(output_file, "w") as f:
            f.write(summary)
        print(summary)
        return

    with open(input_json) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 70)
    lines.append("  petsc Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  petsc Version:   {env.get('software_version', 'N/A')}")
        lines.append(f"  Python Version:    {env.get('python_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:            {env.get('kernel', 'N/A')}")
        lines.append("")

    primary = data.get("primary_benchmark", {})
    if primary:
        params = primary.get("parameters", {})
        lines.append("  --- Primary Benchmark ---")
        lines.append(f"  Description:       {primary.get('description', 'N/A')}")
        lines.append(f"  Parameters:        {params}")
        lines.append("")
        results_summary = primary.get("results_summary", {})
        if isinstance(results_summary, dict):
            for name, res in results_summary.items():
                if isinstance(res, dict):
                    lines.append(f"  {name}:")
                    for k, v in res.items():
                        lines.append(f"    {k}: {v}")
                else:
                    lines.append(f"  {name}: {res}")
                lines.append("")

    micro = data.get("micro_benchmark", {})
    if micro:
        mparams = micro.get("parameters", {})
        lines.append("  --- Micro Benchmarks ---")
        lines.append(f"  Description:       {micro.get('description', 'N/A')}")
        lines.append(f"  Parameters:        {mparams}")
        lines.append("")
        results = micro.get("results", {})
        if isinstance(results, dict):
            for name, res in results.items():
                if isinstance(res, dict):
                    lines.append(f"  {name}:")
                    for k, v in res.items():
                        lines.append(f"    {k}: {v}")
                else:
                    lines.append(f"  {name}: {res}")
                lines.append("")

    lines.append("=" * 70)
    lines.append("  Report generated by petsc Performance Benchmark Workflow")
    lines.append("=" * 70)

    summary = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary)
    print(summary)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)
    generate_summary(sys.argv[1], sys.argv[2])
