name: alertmanager
category: cloud
description: Alertmanager处理客户端应用程序（例如Prometheus服务器）发送的警报。它负责重复数据删除、分组，并将它们路由到正确的接收器集成，例如电子邮件、PagerDuty、OpsGenie或借助Webhook接收器的许多其他机制。它还负责警报的静音和抑制。
environment: ｜
  本应用在Docker环境中运行，安装Docker执行如下命令
  ```
  yum install -y docker
  ```
tags: |
  Alertmanager镜像的Tag由其版本信息和基础镜像版本信息组成，详细内容如下

  |    Tag   |  Currently  |   Architectures  |
  |----------|-------------|------------------|
  |[0.27.0-oe2003sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.27.0/20.03-lts-sp4/Dockerfile)| Alertmanager 0.27.0 on openEuler 20.03-LTS-SP4 | amd64, arm64 |
  |[0.27.0-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.27.0/22.03-lts-sp1/Dockerfile)| Alertmanager 0.27.0 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[0.27.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.27.0/22.03-lts-sp3/Dockerfile)| Alertmanager 0.27.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[0.27.0-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.27.0/22.03-lts-sp4/Dockerfile)| Alertmanager 0.27.0 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[0.27.0-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.27.0/24.03-lts/Dockerfile)| Alertmanager 0.27.0 on openEuler 24.03-LTS | amd64, arm64 |
  |[0.28.0-rc.0-oe2003sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.28.0-rc.0/20.03-lts-sp4/Dockerfile)| Alertmanager 0.28.0-rc.0 on openEuler 20.03-LTS-SP4 | amd64, arm64 |
  |[0.28.0-rc.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.28.0-rc.0/22.03-lts-sp3/Dockerfile)| Alertmanager 0.28.0-rc.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[0.28.0-rc.0-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.28.0-rc.0/22.03-lts-sp4/Dockerfile)| Alertmanager 0.28.0-rc.0 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[0.28.0-rc.0-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/alertmanager/0.28.0-rc.0/24.03-lts/Dockerfile)| Alertmanager 0.28.0-rc.0 on openEuler 24.03-LTS | amd64, arm64 |

download: |
  拉取镜像到本地
  ```
  docker pull openeuler/alertmanager:{Tag}
  ```

usage: |
  - 启动容器
    ```
    docker run -d --name my-alertmanager -p 9093:9093 openeuler/alertmanager:{Tag}
    ```
    用户可根据自身需求选择对应版本的{Tag}、容器启动的选项。`my-alertmanager`启动之后，通过`http://localhost:9093`地址访问该实例。
  
  - 启动参数

    |    Parameter   |  Description  |
    |----------------|---------------|
    | -p 9093:9093  | 通过`localhost:9093`端口暴露`my-alertmanager`实例 |
    | -v /path/to/alertmanager.yml:/etc/prometheus/alertmanager.yml | 指定本地配置文件进行配置 |
    | -v /path/to/persisted/data:/alertmaanger | 用于保留运行数据，这样就不必为每个新启动的容器初始化新数据库 |

  - 容器测试

    查看运行日志
    ```
    docker logs -f my-alertmanager
    ```

    使用shell交互
    ```
    docker exec -it my-alertmanager /bin/bash
    ```

license: Apache-2.0 license
similar_packages:
  - VictoriaMetrics Alertmanager: 这是一个与Prometheus兼容的开源告警管理器，它提供类似于Prometheus Alertmanager的功能。它可以接收来自Prometheus的告警，并根据配置的规则进行处理和发送通知。
  - Alerta: Alerta是一个开源的事件报警工具，它可以集成各种监控系统和服务（包括Prometheus）并提供统一的事件报警和通知管理。它支持自定义规则和插件，可以根据事件的严重性和优先级进行分组和处理，还提供了丰富的通知渠道和可视化界面。
  - Grafana Alerting: Grafana是一个流行的开源数据可视化和仪表盘工具，它的最新版本中引入了Alerting功能。Grafana Alerting可以与Prometheus集成，提供类似于Alertmanager的告警管理和通知功能。它支持灵活的告警规则配置和多种通知渠道。
dependency:
  - N/A