3.3.1-oe2203lts:
  path: spark/3.3.1/22.03-lts/Dockerfile
3.3.2-oe2203lts:
  path: spark/3.3.2/22.03-lts/Dockerfile
3.4.0-oe2203lts:
  path: spark/3.4.0/22.03-lts/Dockerfile
3.5.1-oe2403lts:
  path: spark/3.5.1/24.03-lts/Dockerfile
3.5.3-oe2403lts:
  path: spark/3.5.3/24.03-lts/Dockerfile
3.5.3-oe2203sp3:
  path: spark/3.5.3/22.03-lts-sp3/Dockerfile