#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)
    lines = []
    lines.append("=" * 70)
    lines.append("  CPython Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")
    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  Python Version:    {env.get('software_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:           {env.get('kernel', 'N/A')}")
        lines.append("")
    benchmarks = data.get("benchmarks", {})
    primary = benchmarks.get("primary", {})
    if primary:
        lines.append("  --- pyperformance Benchmarks (Primary) ---")
        lines.append(f"  Description:       {primary.get('description', 'N/A')}")
        lines.append(f"  Tests:             {primary.get('parameters', {}).get('bench_tests', 'N/A')}")
        lines.append("")
        rs = primary.get("results_summary", {})
        header = "    {:<25} {:>12} {:>12} {:>12}".format("benchmark", "mean (ms)", "ops/sec", "min (ms)")
        lines.append(header)
        lines.append("    " + "-" * (len(header) - 4))
        for name in sorted(rs.keys()):
            e = rs[name]
            if isinstance(e, dict) and e:
                lines.append("    {:<25} {:>12.4f} {:>12.2f} {:>12.4f}".format(
                    name[:25], e.get("mean_ms", 0) or 0, e.get("ops_per_sec", 0) or 0, e.get("min_ms", 0) or 0))
        lines.append("")
    micro = benchmarks.get("micro", {})
    if micro:
        lines.append("  --- Micro Benchmarks ---")
        mresults = micro.get("results", {})
        if isinstance(mresults, dict):
            mo = mresults.get("micro_ops", {})
            if isinstance(mo, dict) and mo:
                lines.append("  Micro operations (timeit):")
                for op_name in sorted(mo.keys()):
                    op_data = mo[op_name]
                    if not isinstance(op_data, dict):
                        continue
                    lines.append(f"    [{op_name}]")
                    for size_label in sorted(op_data.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                        e = op_data[size_label]
                        if isinstance(e, dict) and e:
                            lines.append(f"      {size_label:<12}: {e.get('ops_per_sec', 'N/A')} ops/sec")
            ts = mresults.get("thread_scaling", {})
            if isinstance(ts, dict) and ts:
                lines.append("  Thread scaling (GIL limited):")
                for tc in sorted(ts.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                    e = ts[tc]
                    if isinstance(e, dict) and e:
                        lines.append(f"    {tc:<14}: {e.get('ops_per_sec', 'N/A')} ops/sec")
        lines.append("")
    summary = data.get("summary", {})
    if summary:
        lines.append("  --- Overall Summary ---")
        if "avg_ops_per_sec" in summary: lines.append(f"    Avg ops/sec:         {summary['avg_ops_per_sec']}")
        if "max_ops_per_sec" in summary: lines.append(f"    Max ops/sec:         {summary['max_ops_per_sec']}")
        if "avg_mean_ms" in summary: lines.append(f"    Avg mean:            {summary['avg_mean_ms']} ms")
        if "min_mean_ms" in summary: lines.append(f"    Min mean (fastest):  {summary['min_mean_ms']} ms")
        if "thread_scaling_ratio" in summary: lines.append(f"    Thread scaling:      {summary['thread_scaling_ratio']}x (GIL limited)")
        lines.append("")
    lines.append("=" * 70)
    lines.append("  Report generated by CPython Performance Benchmark Workflow")
    lines.append("=" * 70)
    summary_text = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary_text)
    print(summary_text)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)
    generate_summary(sys.argv[1], sys.argv[2])
