#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 70)
    lines.append("  Faiss ARM64 Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Timestamp: {data.get('timestamp', 'N/A')}")
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:   {env.get('architecture', 'N/A')}")
        lines.append(f"  CPU Model:      {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:      {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  Memory (MB):    {env.get('memory_mb', 'N/A')}")
        lines.append(f"  Faiss Version:  {env.get('software_version', 'N/A')}")
        lines.append(f"  Python Version: {env.get('python_version', 'N/A')}")
        lines.append(f"  NumPy Version:  {env.get('numpy_version', 'N/A')}")
        lines.append(f"  OS:             {env.get('os', 'N/A')}")
        lines.append("")

    ann = data.get("primary_benchmark", {})
    if ann:
        params = ann.get("parameters", {})
        k_val = params.get("k", 10)
        lines.append("  --- ANN Search Benchmark (Primary) ---")
        lines.append(f"  Description:    {ann.get('description', 'N/A')}")
        lines.append(f"  Reference:      {ann.get('reference', 'N/A')}")
        lines.append(f"  Dataset:        {params.get('num_vectors', 'N/A')} vectors, {params.get('dimension', 'N/A')} dims, k={k_val}")
        lines.append("")
        results = ann.get("results_summary", {})
        for index_name, res in results.items():
            if "error" in res:
                lines.append(f"  {index_name}: ERROR - {res['error']}")
            else:
                recall_key = f"recall_at_{k_val}"
                lines.append(f"  {index_name}:")
                lines.append(f"    QPS:              {res.get('qps', 'N/A')}")
                lines.append(f"    Recall@{k_val}:       {res.get(recall_key, 'N/A')}")
                lines.append(f"    Build time:       {res.get('build_time_s', 'N/A')}s")
                lines.append(f"    Latency/query:    {res.get('latency_per_query_us', 'N/A')} us")
                lines.append("")

    micro = data.get("micro_benchmark", {})
    if micro:
        mparams = micro.get("parameters", {})
        lines.append("  --- Micro Benchmarks ---")
        lines.append(f"  Description:    {micro.get('description', 'N/A')}")
        lines.append(f"  Reference:      {micro.get('reference', 'N/A')}")
        lines.append(f"  Dataset:        {mparams.get('num_vectors', 'N/A')} vectors, {mparams.get('dimension', 'N/A')} dims")
        lines.append(f"  Avg latency:    {micro.get('avg_latency_ms', 'N/A')}ms")
        lines.append("")
        for test in micro.get("results", []):
            lines.append(f"  {test.get('test', 'N/A')}:")
            lines.append(f"    Avg latency:    {test.get('avg_latency_ms', 'N/A')}ms")
            if "avg_time_s" in test:
                lines.append(f"    Avg time:       {test.get('avg_time_s', 'N/A')}s")
            if "add_rate_per_sec" in test:
                lines.append(f"    Add rate:       {test.get('add_rate_per_sec', 'N/A')} vec/s")
            if "avg_qps" in test:
                lines.append(f"    Avg QPS:        {test.get('avg_qps', 'N/A')}")
            lines.append("")

    lines.append("=" * 70)
    lines.append("  Report generated by Faiss ARM64 Performance Benchmark Workflow")
    lines.append("=" * 70)

    summary = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary)
    print(summary)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)

    input_json = sys.argv[1]
    output_file = sys.argv[2]
    generate_summary(input_json, output_file)
