#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 70)
    lines.append("  LZ4 Source Build & Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  LZ4 Version:       {env.get('software_version', 'N/A')}")
        lines.append(f"  Python Version:    {env.get('python_version', 'N/A')}")
        lines.append(f"  GCC Version:       {env.get('gcc_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:            {env.get('kernel', 'N/A')}")
        lines.append("")

    compression = data.get("benchmarks", {}).get("primary", data.get("primary_benchmark", {}))
    if compression:
        lines.append("  --- Compression Benchmark (Primary) ---")
        lines.append(f"  Description:       {compression.get('description', 'N/A')}")
        lines.append(f"  Reference:         {compression.get('reference', 'N/A')}")
        params = compression.get("parameters", {})
        lines.append(f"  Data sizes:        {params.get('data_size_bytes', 'N/A')}")
        lines.append(f"  Iterations:        {params.get('iterations', 'N/A')}")
        lines.append("")
        results = compression.get("results_summary", {})
        for data_type, res in results.items():
            if isinstance(res, dict):
                lines.append(f"  {data_type}:")
                lines.append(f"    Compress speed:     {res.get('compress_speed_mbs', 'N/A')} MB/s")
                lines.append(f"    Decompress speed:   {res.get('decompress_speed_mbs', 'N/A')} MB/s")
                lines.append(f"    Compression ratio:  {res.get('compression_ratio', 'N/A')}")
                lines.append(f"    Original size:      {res.get('original_size_bytes', 'N/A')} bytes")
                lines.append(f"    Compressed size:    {res.get('compressed_size_bytes', 'N/A')} bytes")
                lines.append("")

    micro = data.get("benchmarks", {}).get("micro", data.get("micro_benchmark", {}))
    if micro:
        mparams = micro.get("parameters", {})
        lines.append("  --- Micro Benchmarks ---")
        lines.append(f"  Description:       {micro.get('description', 'N/A')}")
        lines.append(f"  Block sizes:       {mparams.get('block_sizes', 'N/A')}")
        lines.append(f"  Iterations:        {mparams.get('iterations', 'N/A')}")
        lines.append("")
        results = micro.get("results", {})
        if isinstance(results, dict):
            for test_name, res in results.items():
                if isinstance(res, dict):
                    lines.append(f"  {test_name}:")
                    for k, v in res.items():
                        lines.append(f"    {k}:  {v}")
                    lines.append("")

    summary = data.get("summary", {})
    if summary:
        lines.append("  --- Overall Summary ---")
        if "avg_compress_speed_mbs" in summary:
            lines.append(f"    Avg compress speed:    {summary['avg_compress_speed_mbs']} MB/s")
        if "max_compress_speed_mbs" in summary:
            lines.append(f"    Max compress speed:    {summary['max_compress_speed_mbs']} MB/s")
        if "avg_decompress_speed_mbs" in summary:
            lines.append(f"    Avg decompress speed:  {summary['avg_decompress_speed_mbs']} MB/s")
        if "max_decompress_speed_mbs" in summary:
            lines.append(f"    Max decompress speed:  {summary['max_decompress_speed_mbs']} MB/s")
        if "avg_compression_ratio" in summary:
            lines.append(f"    Avg compression ratio: {summary['avg_compression_ratio']}")
        if "micro_avg_compress_speed_mbs" in summary:
            lines.append(f"    Micro avg compress:    {summary['micro_avg_compress_speed_mbs']} MB/s")
        if "multithread_scaling_ratio" in summary:
            lines.append(f"    Multithread scaling:    {summary['multithread_scaling_ratio']}x")
        lines.append("")

    lines.append("=" * 70)
    lines.append("  Report generated by LZ4 Source Build & Performance Benchmark Workflow")
    lines.append("=" * 70)

    summary = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary)
    print(summary)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)

    input_json = sys.argv[1]
    output_file = sys.argv[2]
    generate_summary(input_json, output_file)
