name: prometheus-pushgateway
category: cloud
description: Prometheus Pushgateway的存在是为了允许临时作业和批处理作业将其指标公开给Prometheus。由于此类工作可能存在的时间不够长而无法被删除，因此他们可以将其指标推送到Pushgateway。然后Pushgateway将这些指标公开给Prometheus。
environment: |
  本应用在Docker环境中运行，安装Docker执行如下命令
  ```
  yum install -y docker
  ```
tags: |
  Prometheus-pushgateway镜像的Tag由其版本信息和基础镜像版本信息组成，详细内容如下

  |    Tag   |  Currently  |   Architectures  |
  |----------|-------------|------------------|
  |[1.7.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/prometheus-pushgateway/1.7.0/22.03-lts-sp3/Dockerfile)| Prometheus-pushgateway 1.7.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[1.10.0-oe2003sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/prometheus-pushgateway/1.10.0/20.03-lts-sp4/Dockerfile)| Prometheus-pushgateway 1.10.0 on openEuler 20.03-LTS-SP4 | amd64, arm64 |
  |[1.10.0-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/prometheus-pushgateway/1.10.0/22.03-lts-sp1/Dockerfile)| Prometheus-pushgateway 1.10.0 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[1.10.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/prometheus-pushgateway/1.10.0/22.03-lts-sp3/Dockerfile)| Prometheus-pushgateway 1.10.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[1.10.0-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/prometheus-pushgateway/1.10.0/22.03-lts-sp4/Dockerfile)| Prometheus-pushgateway 1.10.0 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[1.10.0-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/prometheus-pushgateway/1.10.0/24.03-lts/Dockerfile)| Prometheus-pushgateway 1.10.0 on openEuler 24.03-LTS | amd64, arm64 |

download: |
  拉取镜像到本地
  ```
  docker pull openeuler/prometheus-pushgateway:{Tag}
  ```

usage: |
  - 启动容器
    ```
    docker run -d --name my-prometheus-pushgateway -p 9091:9091 openeuler/prometheus-pushgateway:{Tag}
    ```
    用户可根据自身需求选择对应版本的{Tag}、容器启动的选项。`my-prometheus-pushgateway`启动之后，通过`http://localhost:9091`访问Prometheus-pushgateway服务。
  
  - 启动参数

    |    Parameter   |  Description  |
    |----------------|---------------|
    | -p 9091:9091	 | 暴露Prometheus-pushgateway服务端口 |

  - 容器测试

    查看运行日志
    ```
    docker logs -f my-prometheus-pushgateway
    ```

    使用shell交互
    ```
    docker exec -it my-prometheus-pushgateway /bin/bash
    ```

license: Apache-2.0 license
similar_packages:
  - N/A
dependency:
  - N/A