# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  tgi-service:
    image: openeuler/text-generation-inference-cpu:2.4.0-oe2403lts
    container_name: tgi-xeon-server
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:80
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      host_ip: ${host_ip}
      LLM_ENDPOINT_PORT: ${LLM_ENDPOINT_PORT}
    command: --model-id ${LLM_MODEL_ID} --cuda-graphs 0
  llm_faqgen:
    image: openeuler/llm-faqgen:1.2-oe2403lts
    container_name: llm-faqgen-server
    depends_on:
      - tgi-service
    ports:
      - ${LLM_SERVICE_PORT:-9000}:9000
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      FAQGen_COMPONENT_NAME: ${FAQGen_COMPONENT_NAME}
      LOGFLAG: ${LOGFLAG:-False}
    restart: unless-stopped
  faqgen-xeon-backend-server:
    image: openeuler/faqgen:1.2-oe2403lts
    container_name: faqgen-xeon-backend-server
    depends_on:
      - tgi-service
      - llm_faqgen
    ports:
      - "8888:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - LLM_SERVICE_HOST_IP=${LLM_SERVICE_HOST_IP}
      - LLM_SERVICE_PORT=${LLM_SERVICE_PORT}
    ipc: host
    restart: always
  faqgen-xeon-ui-server:
    image: openeuler/faqgen-ui:1.2-oe2403lts
    container_name: faqgen-xeon-ui-server
    depends_on:
      - faqgen-xeon-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - FAQ_BASE_URL=${BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always
networks:
  default:
    driver: bridge