name: grafana
category: cloud
description: Grafana是一个开源的数据可视化和监控平台。它提供了丰富的仪表盘和图表，用于实时监控和分析数据，帮助用户可视化数据并进行数据驱动的决策。
environment: |
  本应用在Docker环境中运行，安装Docker执行如下命令
  ```
  yum install -y docker
  ```
tags: |
  Grafana镜像的Tag由其版本信息和基础镜像版本信息组成，详细内容如下

  |    Tag   |  Currently  |   Architectures  |
  |----------|-------------|------------------|
  |[12.1.1-oe2403sp2](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/12.1.1/24.03-lts-sp2/Dockerfile) | grafana 12.1.1 on openEuler 24.03-LTS-SP2 | amd64, arm64 |
  |[7.5.11-oe2203lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/7.5.1/22.03-lts/Dockerfile)| Grafana 7.5.1 on openEuler 22.03-LTS | amd64, arm64 |
  |[10.4.1-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/10.4.1/22.03-lts-sp3/Dockerfile)| Grafana 10.4.1 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[11.1.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.1.0/22.03-lts-sp3/Dockerfile)| Grafana 11.1.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[11.2.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.2.0/22.03-lts-sp3/Dockerfile)| Grafana 11.2.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[11.2.2-oe2003sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.2.2/20.03-lts-sp4/Dockerfile)| Grafana 11.2.2 on openEuler 20.03-LTS-SP4 | amd64, arm64 |
  |[11.2.2-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.2.2/22.03-lts-sp1/Dockerfile)| Grafana 11.2.2 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[11.2.2-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.2.2/22.03-lts-sp3/Dockerfile)| Grafana 11.2.2 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[11.2.2-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.2.2/22.03-lts-sp4/Dockerfile)| Grafana 11.2.2 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[11.2.2-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.2.2/24.03-lts/Dockerfile)| Grafana 11.2.2 on openEuler 24.03-LTS | amd64, arm64 |
  |[11.3.0-oe2203sp1](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.3.0/22.03-lts-sp1/Dockerfile)| Grafana 11.3.0 on openEuler 22.03-LTS-SP1 | amd64, arm64 |
  |[11.3.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.3.0/22.03-lts-sp3/Dockerfile)| Grafana 11.3.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |
  |[11.3.0-oe2203sp4](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.3.0/22.03-lts-sp4/Dockerfile)| Grafana 11.3.0 on openEuler 22.03-LTS-SP4 | amd64, arm64 |
  |[11.3.0-oe2403lts](https://gitee.com/openeuler/openeuler-docker-images/blob/master/Cloud/grafana/11.3.0/24.03-lts/Dockerfile)| Grafana 11.3.0 on openEuler 24.03-LTS | amd64, arm64 |

download: |
  拉取镜像到本地
  ```
  docker pull openeuler/grafana:{Tag}
  ```

usage: |
  - 启动容器
    ```
    docker run -d --name my-grafana -p 3000:3000 openeuler/grafana:{Tag}
    ```
    用户可根据自身需求选择对应版本的{Tag}、容器启动的选项。`my-grafana`启动之后，通过`http://localhost:3000`访问服务。
  
  - 启动参数

    |    Parameter   |  Description  |
    |----------------|---------------|
    | -p 3000:3000	   | 通过`localhost:3000`暴露实例 |
    | -v /path/to/grafana/provisioning/files/:/etc/grafana/provisioning/ | 使用本地配置文件进行配置，详情查看[documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/) |
    | -v /path/to/persisted/data:/var/lib/grafana	| 用于保留运行数据，这样就不必为每个新启动的容器初始化新数据库 |

  - 容器测试

    查看运行日志
    ```
    docker logs -f my-grafana
    ```

    使用shell交互
    ```
    docker exec -it my-grafana /bin/bash
    ```

license: AGPL-3.0 license
similar_packages:
  - Kibana: 一个开源的数据可视化工具，与Elasticsearch配合使用，用于实时分析和可视化日志数据。
  - Tableau: 一款商业化的数据可视化工具，提供了丰富的数据分析和可视化功能，适用于各种数据源和业务场景。
  - Superset: 一个开源的数据探索和可视化平台，支持广泛的数据源和可视化图表，并具有灵活的仪表盘和报表定制能力。
  - Redash: 一个开源的数据查询和可视化工具，支持多种数据源和查询语言，并提供共享查询和仪表盘的功能。
dependency:
  - N/A


homepage: https://github.com/grafana/grafana
upstream:
  version_url: grafana/grafana
  version_prefix: v
  version_filter: rc;security
  backend: GitHub
  version_scheme: RPM