name: Traefik
category: cloud
description: Traefik（发音和traffic相同，采用Golang编写）是一个云原生的新型的HTTP反向代理、负载均衡软件。Traefik负责接收系统的请求，然后使用合适的组件来对这些请求进行处理。Traefik兼容所有主流的集群技术，比如Kubernetes，Docker，Docker Swarm，AWS，Mesos，Marathon等。
environment: |
  本应用在Docker环境中运行，安装Docker执行如下命令
  ```
  yum install -y docker
  ```
tags: |
  Traefik镜像的Tag由其版本信息和基础镜像版本信息组成，详细内容如下

  |    Tag   |  Currently  |   Architectures  |
  |----------|-------------|------------------|
  |[2.11.0-oe2203sp3](https://gitee.com/openeuler/openeuler-docker-images/blob/master/traefik/2.11.0/22.03-lts-sp3/Dockerfile)| Traefik 2.11.0 on openEuler 22.03-LTS-SP3 | amd64, arm64 |

download: |
  拉取镜像到本地
  ```
  docker pull openeuler/traefik:{Tag}
  ```

usage: |
  - 启动容器
    ```
    docker run -d --name my-traefik -p 80:80 openeuler/traefik:{Tag}
    ```
    用户可根据自身需求选择对应版本的{Tag}、容器启动的选项。
    `my-traefik`启动之后，通过`localhost:80`访问traefik反向代理服务。
  
  - 启动参数

    |    Parameter   |  Description  |
    |----------------|---------------|
    | -p 80:80	     | 暴露traefik反向代理服务端口 |
    | -v /path/to/traefik.yml:/etc/traefik/traefik.yml | 指定使用的`traefik.yml`配置文件 |

  - 容器测试

    查看运行日志
    ```
    docker logs -f my-traefik
    ```

    使用shell交互
    ```
    docker exec -it my-traefik /bin/bash
    ```

license: MIT license
similar_packages:
  - Nginx: Nginx是一款高性能的反向代理和Web服务器软件。它支持负载均衡、SSL/TLS 终止、缓存和许多其他功能。与Traefik类似，Nginx也可以用于容器化环境中。
  - HAProxy: HAProxy是一款高可用性的TCP/HTTP反向代理和负载均衡软件。它具有高性能和可靠性，并支持动态配置和健康检查。
  - Envoy: Envoy是一个开源的边缘和服务代理，具有动态配置、负载均衡、故障恢复和流量监控等功能。它被广泛用于云原生环境和微服务架构中。
  - Caddy: Caddy是一款现代化的Web服务器和反向代理软件，具有自动HTTPS、自动HTTP/2和易于使用的配置功能。它支持动态代理和负载均衡，并适用于容器化环境。
dependency:
  - N/A